# MIT License
#
# SPDX-FileCopyrightText: Copyright (c) 2024 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
name: 'bibcop-action'
description: 'Check the quality of .bib files'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: 'docker'
  image: 'docker://yegor256/bibcop-action:latest'
inputs:
  opts:
    description: 'Command-line options for the bibcop tool'
    required: false
    default: ''
