---
name: shellcheck
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
