# SPDX-FileCopyrightText: Copyright (c) 2024 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: test
'on':
  push:
  pull_request:
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: |
          cat > test.bib << EOT
          @misc{x,
            title={{Hello, World!}},
            author={Bugayenko, Yegor},
            year={2024}
          }
          EOT
      - uses: ./
        with:
          opts: --verbose
