name: test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          cmd: latexmk
          path: .
          opts: -pdf test
          packages: ffcode fvextra catchfile xstring framed environ upquote
