---
name: test
'on':
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat > test.bib << EOT
          @misc{x,
            title={{Hello, World!}},
            author={Bugayenko, Yegor},
            year={2024}
          }
          EOT
      - uses: ./
        with:
          opts: --verbose
